import type {
  User,
  Deposit,
  Truck,
  Product,
  Order,
  OrderItem,
  OrderRoute,
  Stock,
  Supplier,
  SupplyRoute,
  DashboardStats,
  MonthlyPerformanceData,
} from "@/types";

// ─── 1. Products (16 entries across refrigerated, fragile, industrial, and consumer categories)
export const PRODUCTS: Product[] = [
  {
    id: "PROD-001",
    name: "Fresh Milk - Leite Pasteurizado Tipo A da Serra",
    is_cold: true,
    is_fragile: false,
    expire_date: "2026-05-15",
    price: 4.8,
    size: '{"length":10,"width":10,"height":20}',
    volume: 0.002,
    weight: 1.0,
  },
  {
    id: "PROD-002",
    name: "Crystal Vase - Cristais Artesanais de Petrópolis",
    is_cold: false,
    is_fragile: true,
    price: 120.0,
    size: '{"length":30,"width":30,"height":40}',
    volume: 0.036,
    weight: 2.5,
  },
  {
    id: "PROD-003",
    name: "Smartphone X - Terminal Móvel de Rastreamento",
    is_cold: false,
    is_fragile: false,
    price: 899.99,
    size: '{"length":15,"width":8,"height":2}',
    volume: 0.00024,
    weight: 0.2,
  },
  {
    id: "PROD-004",
    name: "Frozen Pizza - Pizza Artesanal de Forno de Pedra",
    is_cold: true,
    is_fragile: false,
    expire_date: "2026-10-30",
    price: 28.5,
    size: '{"length":30,"width":30,"height":3}',
    volume: 0.0027,
    weight: 0.5,
  },
  {
    id: "PROD-005",
    name: "Office Chair - Cadeira Ergonômica SerraOffice",
    is_cold: false,
    is_fragile: false,
    price: 450.0,
    size: '{"length":60,"width":60,"height":100}',
    volume: 0.36,
    weight: 12.0,
  },
  {
    id: "PROD-006",
    name: "Gaming Laptop - Workstation Portátil de Engenharia",
    is_cold: false,
    is_fragile: true,
    price: 3500.0,
    size: '{"length":40,"width":30,"height":5}',
    volume: 0.006,
    weight: 3.0,
  },
  {
    id: "PROD-007",
    name: "Red Wine Box - Vinho Fino Tinto Reserva da Serra",
    is_cold: false,
    is_fragile: true,
    expire_date: "2029-12-31",
    price: 180.0,
    size: '{"length":30,"width":20,"height":30}',
    volume: 0.018,
    weight: 9.0,
  },
  {
    id: "PROD-008",
    name: "Industrial Drill - Furadeira & Martelete Industrial",
    is_cold: false,
    is_fragile: false,
    price: 520.0,
    size: '{"length":40,"width":15,"height":25}',
    volume: 0.015,
    weight: 5.5,
  },
  {
    id: "PROD-009",
    name: "Cerveja Artesanal Imperial IPA 500ml",
    is_cold: false,
    is_fragile: true,
    expire_date: "2027-02-28",
    price: 18.9,
    size: '{"length":12,"width":12,"height":25}',
    volume: 0.001,
    weight: 0.8,
  },
  {
    id: "PROD-010",
    name: "Hortaliças Hidropônicas Embaladas Premium",
    is_cold: true,
    is_fragile: false,
    expire_date: "2026-04-25",
    price: 7.5,
    size: '{"length":20,"width":20,"height":15}',
    volume: 0.005,
    weight: 0.4,
  },
  {
    id: "PROD-011",
    name: "Filé de Truta Fresca Congelada de Lumiar",
    is_cold: true,
    is_fragile: false,
    expire_date: "2026-08-30",
    price: 65.0,
    size: '{"length":25,"width":15,"height":8}',
    volume: 0.003,
    weight: 1.0,
  },
  {
    id: "PROD-012",
    name: "Lote de Confecção & Moda Íntima Friburgo (50 un)",
    is_cold: false,
    is_fragile: false,
    price: 1200.0,
    size: '{"length":50,"width":50,"height":40}',
    volume: 0.1,
    weight: 15.0,
  },
  {
    id: "PROD-013",
    name: "Galão de Água Mineral Natural da Serra 20L",
    is_cold: false,
    is_fragile: false,
    price: 14.0,
    size: '{"length":30,"width":30,"height":50}',
    volume: 0.025,
    weight: 20.0,
  },
  {
    id: "PROD-014",
    name: "Queijo Suíço Gruyère Friburguense Maturado",
    is_cold: true,
    is_fragile: false,
    expire_date: "2026-09-15",
    price: 85.0,
    size: '{"length":20,"width":20,"height":10}',
    volume: 0.004,
    weight: 1.2,
  },
  {
    id: "PROD-015",
    name: "Frango Resfriado Inteiro Vale do Rio Preto",
    is_cold: true,
    is_fragile: false,
    expire_date: "2026-05-10",
    price: 22.0,
    size: '{"length":25,"width":20,"height":15}',
    volume: 0.005,
    weight: 2.5,
  },
  {
    id: "PROD-016",
    name: "Café Especial Gourmet Torrado em Grãos 1kg",
    is_cold: false,
    is_fragile: false,
    expire_date: "2027-06-30",
    price: 68.0,
    size: '{"length":15,"width":10,"height":25}',
    volume: 0.003,
    weight: 1.0,
  },
];

export const getProductById = (id: string): Product | undefined =>
  PRODUCTS.find((p) => p.id === id);

// ─── 2. Suppliers (10 suppliers in Região Serrana)
export const SUPPLIERS: Supplier[] = [
  {
    id: "SUP-001",
    name: "Horta Serrana Orgânicos & Hortifruti",
    address: "Estrada Terê-Fri, Km 18, Teresópolis - RJ",
    latitude: -22.4123,
    longitude: -42.9656,
  },
  {
    id: "SUP-002",
    name: "Queijaria Suíça & Laticínios Friburgo",
    address: "Circuito Terê-Fri, Conquista, Nova Friburgo - RJ",
    latitude: -22.2819,
    longitude: -42.5311,
  },
  {
    id: "SUP-003",
    name: "Cervejaria Artesanal Imperial de Petrópolis",
    address: "Rua Bingen, 1400, Bingen, Petrópolis - RJ",
    latitude: -22.505,
    longitude: -43.1789,
  },
  {
    id: "SUP-004",
    name: "Cooperativa Avícola & Frigorífico Vale do Rio Preto",
    address: "Rodovia RJ-134, Km 10, São José do Vale do Rio Preto - RJ",
    latitude: -22.1528,
    longitude: -42.9239,
  },
  {
    id: "SUP-005",
    name: "Polo Têxtil e Moda Íntima Olaria",
    address: "Rua Presidente Vargas, 350, Olaria, Nova Friburgo - RJ",
    latitude: -22.298,
    longitude: -42.539,
  },
  {
    id: "SUP-006",
    name: "Água Mineral Natural da Serra dos Órgãos",
    address: "Estrada da Caneca Fina, 800, Guapimirim - RJ",
    latitude: -22.5367,
    longitude: -42.9819,
  },
  {
    id: "SUP-007",
    name: "Laticínios Bela Vista & Queijos de Cordeiro",
    address: "Av. Raul Veiga, 520, Centro, Cordeiro - RJ",
    latitude: -21.9861,
    longitude: -42.3611,
  },
  {
    id: "SUP-008",
    name: "Fruticultura & Trutas Frescas de Lumiar",
    address: "Estrada de Lumiar, Km 8, Nova Friburgo - RJ",
    latitude: -22.355,
    longitude: -42.321,
  },
  {
    id: "SUP-009",
    name: "Distribuidora Imperial de Bebidas & Alimentos",
    address: "Rua do Imperador, 600, Centro, Petrópolis - RJ",
    latitude: -22.51,
    longitude: -43.18,
  },
  {
    id: "SUP-010",
    name: "Café Especial das Alturas de Cantagalo",
    address: "Fazenda Santa Rita, Estrada de Euclidelândia, Cantagalo - RJ",
    latitude: -21.975,
    longitude: -42.37,
  },
];

// ─── 3. Deposits / Warehouses (8 hubs in Região Serrana)
export const DEPOSITS: Deposit[] = [
  {
    id: "WH-001",
    location: "Petrópolis Hub - Itaipava (Lat: -22.3842, Lon: -43.1311)",
    size: '{"length":100,"width":100,"height":10}',
    volume_actual: 24.5,
    volume_max: 100000.0,
    has_refrigeration: true,
    fuel_price: 5.89,
    truck_capacity: 6,
    parking_capacity: 6,
  },
  {
    id: "WH-002",
    location: "Teresópolis Depot - Alto (Lat: -22.4350, Lon: -42.9800)",
    size: '{"length":60,"width":50,"height":8}',
    volume_actual: 8.2,
    volume_max: 35000.0,
    has_refrigeration: false,
    fuel_price: 6.15,
    truck_capacity: 4,
    parking_capacity: 4,
  },
  {
    id: "WH-003",
    location: "Nova Friburgo Facility - Olaria (Lat: -22.3000, Lon: -42.5400)",
    size: '{"length":90,"width":70,"height":10}',
    volume_actual: 18.9,
    volume_max: 80000.0,
    has_refrigeration: true,
    fuel_price: 5.95,
    truck_capacity: 6,
    parking_capacity: 6,
  },
  {
    id: "WH-004",
    location: "Cachoeiras de Macacu Valley Cross-Dock (Lat: -22.4633, Lon: -42.6528)",
    size: '{"length":70,"width":60,"height":9}',
    volume_actual: 12.0,
    volume_max: 45000.0,
    has_refrigeration: false,
    fuel_price: 5.82,
    truck_capacity: 5,
    parking_capacity: 5,
  },
  {
    id: "WH-005",
    location: "Guapimirim Foothills Hub (Lat: -22.5367, Lon: -42.9819)",
    size: '{"length":65,"width":55,"height":9}',
    volume_actual: 9.4,
    volume_max: 40000.0,
    has_refrigeration: true,
    fuel_price: 5.85,
    truck_capacity: 4,
    parking_capacity: 4,
  },
  {
    id: "WH-006",
    location: "São José do Vale do Rio Preto Depo (Lat: -22.1528, Lon: -42.9239)",
    size: '{"length":55,"width":50,"height":8}',
    volume_actual: 6.8,
    volume_max: 30000.0,
    has_refrigeration: true,
    fuel_price: 5.98,
    truck_capacity: 4,
    parking_capacity: 4,
  },
  {
    id: "WH-007",
    location: "Cordeiro & Cantagalo Central Logistics (Lat: -21.9861, Lon: -42.3611)",
    size: '{"length":80,"width":65,"height":10}',
    volume_actual: 15.6,
    volume_max: 55000.0,
    has_refrigeration: false,
    fuel_price: 6.09,
    truck_capacity: 5,
    parking_capacity: 5,
  },
  {
    id: "WH-008",
    location: "Bom Jardim Agro Terminal (Lat: -22.1500, Lon: -42.4167)",
    size: '{"length":60,"width":50,"height":8}',
    volume_actual: 5.2,
    volume_max: 32000.0,
    has_refrigeration: true,
    fuel_price: 6.02,
    truck_capacity: 3,
    parking_capacity: 3,
  },
];

export const getDepositById = (id: string): Deposit | undefined =>
  DEPOSITS.find((d) => d.id === id);

export const getDepositLabel = (deposit: Deposit): string =>
  deposit.location || `Warehouse ${deposit.id}`;

// ─── 4. Users (20 users across Região Serrana)
export const USERS: User[] = [
  {
    id: "USR-001",
    name: "Alice Admin",
    email: "alice@logisys.com",
    role: "admin",
    rawRole: "admin",
    work_position: "System Administrator",
    address: "Rua do Imperador, Centro, Petrópolis - RJ",
    wage: 65.0,
  },
  {
    id: "USR-002",
    name: "Bob Worker",
    email: "bob@logisys.com",
    role: "worker",
    rawRole: "warehouse_worker",
    work_position: "Warehouse Worker",
    address: "Estrada União e Indústria, Itaipava, Petrópolis - RJ",
    wage: 42.0,
  },
  {
    id: "USR-003",
    name: "Charlie Driver",
    email: "charlie@logisys.com",
    role: "worker",
    rawRole: "truck_driver",
    work_position: "Truck Driver",
    address: "Av. Alberto Braune, Centro, Nova Friburgo - RJ",
    wage: 55.0,
  },
  {
    id: "USR-004",
    name: "David Client",
    email: "david@logisys.com",
    role: "client",
    rawRole: "client",
    address: "Av. Reta da Várzea, Várzea, Teresópolis - RJ",
    wage: 0.0,
  },
  {
    id: "USR-005",
    name: "Eve Client",
    email: "eve@logisys.com",
    role: "client",
    rawRole: "client",
    address: "Rua Monte Líbano, Centro, Nova Friburgo - RJ",
    wage: 0.0,
  },
  {
    id: "USR-006",
    name: "Frank Driver",
    email: "frank@logisys.com",
    role: "worker",
    rawRole: "truck_driver",
    work_position: "Truck Driver",
    address: "Estrada Terê-Fri, Km 12, Teresópolis - RJ",
    wage: 50.0,
  },
  {
    id: "USR-007",
    name: "Grace Worker",
    email: "grace@logisys.com",
    role: "worker",
    rawRole: "warehouse_worker",
    work_position: "Warehouse Worker",
    address: "Rua General Osório, Centro, Nova Friburgo - RJ",
    wage: 40.0,
  },
  {
    id: "USR-008",
    name: "Henry Client",
    email: "henry@logisys.com",
    role: "client",
    rawRole: "client",
    address: "Rua Visconde de Uruguai, Cachoeiras de Macacu - RJ",
    wage: 0.0,
  },
  {
    id: "USR-009",
    name: "Ivy Client",
    email: "ivy@logisys.com",
    role: "client",
    rawRole: "client",
    address: "Av. Dedo de Deus, Guapimirim - RJ",
    wage: 0.0,
  },
  {
    id: "USR-010",
    name: "Jack Worker",
    email: "jack@logisys.com",
    role: "worker",
    rawRole: "warehouse_worker",
    work_position: "Warehouse Worker",
    address: "Rua Cel. Veiga, Petrópolis - RJ",
    wage: 38.0,
  },
  {
    id: "USR-011",
    name: "Karina Driver",
    email: "karina@logisys.com",
    role: "worker",
    rawRole: "truck_driver",
    work_position: "Truck Driver",
    address: "Rua Bingen, Bingen, Petrópolis - RJ",
    wage: 52.0,
  },
  {
    id: "USR-012",
    name: "Lucas Worker",
    email: "lucas@logisys.com",
    role: "worker",
    rawRole: "warehouse_worker",
    work_position: "Warehouse Worker",
    address: "Av. Feliciano Sodré, Várzea, Teresópolis - RJ",
    wage: 39.0,
  },
  {
    id: "USR-013",
    name: "Mariana Client",
    email: "mariana@logisys.com",
    role: "client",
    rawRole: "client",
    address: "Rua João Ferreira, Centro, São José do Vale do Rio Preto - RJ",
    wage: 0.0,
  },
  {
    id: "USR-014",
    name: "Nelson Client",
    email: "nelson@logisys.com",
    role: "client",
    rawRole: "client",
    address: "Av. Raul Veiga, Centro, Cordeiro - RJ",
    wage: 0.0,
  },
  {
    id: "USR-015",
    name: "Olivia Driver",
    email: "olivia@logisys.com",
    role: "worker",
    rawRole: "truck_driver",
    work_position: "Truck Driver",
    address: "Rua Presidente Vargas, Olaria, Nova Friburgo - RJ",
    wage: 54.0,
  },
  {
    id: "USR-016",
    name: "Paulo Worker",
    email: "paulo@logisys.com",
    role: "worker",
    rawRole: "warehouse_worker",
    work_position: "Warehouse Worker",
    address: "Rodovia RJ-116, Km 35, Cachoeiras de Macacu - RJ",
    wage: 41.0,
  },
  {
    id: "USR-017",
    name: "Renata Client",
    email: "renata@logisys.com",
    role: "client",
    rawRole: "client",
    address: "Rua Dr. Moacyr Freijanes, Centro, Bom Jardim - RJ",
    wage: 0.0,
  },
  {
    id: "USR-018",
    name: "Sergio Client",
    email: "sergio@logisys.com",
    role: "client",
    rawRole: "client",
    address: "Praça Miguel de Carvalho, Centro, Cantagalo - RJ",
    wage: 0.0,
  },
  {
    id: "USR-019",
    name: "Tatiana Driver",
    email: "tatiana@logisys.com",
    role: "worker",
    rawRole: "truck_driver",
    work_position: "Truck Driver",
    address: "Estrada Bananal, Guapimirim - RJ",
    wage: 51.0,
  },
  {
    id: "USR-020",
    name: "Valter Worker",
    email: "valter@logisys.com",
    role: "worker",
    rawRole: "warehouse_worker",
    work_position: "Warehouse Worker",
    address: "Rua Pereira Sobrinho, Cordeiro - RJ",
    wage: 40.0,
  },
];

export const getUserById = (id: string): User | undefined =>
  USERS.find((u) => u.id === id);

// ─── 5. Trucks (8 fleet vehicles)
export const TRUCKS: Truck[] = [
  {
    id: "TRK-001",
    model: "Volvo FH16 540",
    size: '{"length":13.6,"width":2.5,"height":2.7}',
    volume_actual: 0.0,
    volume_max: 90.0,
    weight_actual: 0.0,
    weight_max: 25000.0,
    is_delivering: false,
    is_valid: true,
    is_traveling: false,
    current_deposit_id: "WH-001",
    has_refrigeration: true,
    speed: 85.0,
    fuel_capacity: 500.0,
    fuel_current: 450.0,
    fuel_consumption: 0.3,
    wear_percentage: 15,
    truck_maintenance: 0,
  },
  {
    id: "TRK-002",
    model: "Scania R500 V8",
    size: '{"length":13.6,"width":2.5,"height":2.7}',
    volume_actual: 0.036,
    volume_max: 90.0,
    weight_actual: 2.5,
    weight_max: 25000.0,
    is_delivering: true,
    is_valid: true,
    is_traveling: true,
    origin_deposit_id: "WH-001",
    destination_deposit_id: "WH-002",
    estimated_time: "2026-03-26T14:00:00",
    has_refrigeration: false,
    speed: 80.0,
    fuel_capacity: 600.0,
    fuel_current: 320.0,
    fuel_consumption: 0.35,
    wear_percentage: 25,
    truck_maintenance: 1,
  },
  {
    id: "TRK-003",
    model: "MAN TGX 28.480",
    size: '{"length":13.6,"width":2.5,"height":2.7}',
    volume_actual: 0.0,
    volume_max: 90.0,
    weight_actual: 0.0,
    weight_max: 25000.0,
    is_delivering: false,
    is_valid: true,
    is_traveling: false,
    current_deposit_id: "WH-003",
    has_refrigeration: true,
    speed: 82.0,
    fuel_capacity: 550.0,
    fuel_current: 480.0,
    fuel_consumption: 0.32,
    wear_percentage: 10,
    truck_maintenance: 0,
  },
  {
    id: "TRK-004",
    model: "Iveco S-Way 480",
    size: '{"length":12,"width":2.4,"height":2.5}',
    volume_actual: 0.0,
    volume_max: 75.0,
    weight_actual: 0.0,
    weight_max: 18000.0,
    is_delivering: false,
    is_valid: true,
    is_traveling: false,
    current_deposit_id: "WH-002",
    has_refrigeration: false,
    speed: 78.0,
    fuel_capacity: 450.0,
    fuel_current: 390.0,
    fuel_consumption: 0.28,
    wear_percentage: 20,
    truck_maintenance: 1,
  },
  {
    id: "TRK-005",
    model: "Mercedes-Benz Actros 2651",
    size: '{"length":14,"width":2.6,"height":2.8}',
    volume_actual: 0.12,
    volume_max: 95.0,
    weight_actual: 18.0,
    weight_max: 26000.0,
    is_delivering: true,
    is_valid: true,
    is_traveling: true,
    origin_deposit_id: "WH-003",
    destination_deposit_id: "WH-007",
    estimated_time: "2026-03-27T16:30:00",
    has_refrigeration: true,
    speed: 84.0,
    fuel_capacity: 600.0,
    fuel_current: 410.0,
    fuel_consumption: 0.33,
    wear_percentage: 12,
    truck_maintenance: 0,
  },
  {
    id: "TRK-006",
    model: "Volkswagen Delivery 11.180",
    size: '{"length":8.5,"width":2.3,"height":2.4}',
    volume_actual: 0.0,
    volume_max: 45.0,
    weight_actual: 0.0,
    weight_max: 8000.0,
    is_delivering: false,
    is_valid: true,
    is_traveling: false,
    current_deposit_id: "WH-005",
    has_refrigeration: true,
    speed: 90.0,
    fuel_capacity: 250.0,
    fuel_current: 220.0,
    fuel_consumption: 0.22,
    wear_percentage: 8,
    truck_maintenance: 0,
  },
  {
    id: "TRK-007",
    model: "DAF XF 530 Super Space",
    size: '{"length":13.8,"width":2.5,"height":2.7}',
    volume_actual: 0.0,
    volume_max: 92.0,
    weight_actual: 0.0,
    weight_max: 25000.0,
    is_delivering: false,
    is_valid: true,
    is_traveling: false,
    current_deposit_id: "WH-004",
    has_refrigeration: false,
    speed: 82.0,
    fuel_capacity: 580.0,
    fuel_current: 520.0,
    fuel_consumption: 0.31,
    wear_percentage: 15,
    truck_maintenance: 0,
  },
  {
    id: "TRK-008",
    model: "Scania P360 Frigorífico",
    size: '{"length":10.5,"width":2.5,"height":2.6}',
    volume_actual: 0.0,
    volume_max: 60.0,
    weight_actual: 0.0,
    weight_max: 15000.0,
    is_delivering: false,
    is_valid: true,
    is_traveling: false,
    current_deposit_id: "WH-006",
    has_refrigeration: true,
    speed: 80.0,
    fuel_capacity: 400.0,
    fuel_current: 350.0,
    fuel_consumption: 0.26,
    wear_percentage: 10,
    truck_maintenance: 0,
  },
];

export const getTruckById = (id: string): Truck | undefined =>
  TRUCKS.find((t) => t.id === id);

// ─── 6. Orders (12 orders across Região Serrana)
export const ORDERS: Order[] = [
  {
    id: "ORD-001",
    client_id: "USR-004",
    final_destination: "Av. Reta da Várzea, Várzea, Teresópolis - RJ",
    time_limit: "2026-03-30",
    price: 50.0,
    status: "Pending",
    supplier_id: "SUP-002",
    supplier_delivery: false,
    distance_km: 48.5,
  },
  {
    id: "ORD-002",
    client_id: "USR-005",
    final_destination: "Rua Monte Líbano, Centro, Nova Friburgo - RJ",
    time_limit: "2026-03-28",
    price: 950.0,
    status: "Shipped",
    supplier_id: "SUP-001",
    supplier_delivery: true,
    distance_km: 72.3,
  },
  {
    id: "ORD-003",
    client_id: "USR-004",
    final_destination: "Av. Reta da Várzea, Várzea, Teresópolis - RJ",
    time_limit: "2026-03-20",
    price: 15.0,
    status: "Delivered",
    supplier_delivery: true,
    distance_km: 35.0,
  },
  {
    id: "ORD-004",
    client_id: "USR-008",
    final_destination: "Rua Visconde de Uruguai, Cachoeiras de Macacu - RJ",
    time_limit: "2026-04-05",
    price: 2400.0,
    status: "Pending",
    supplier_id: "SUP-003",
    supplier_delivery: false,
    distance_km: 88.0,
  },
  {
    id: "ORD-005",
    client_id: "USR-009",
    final_destination: "Av. Dedo de Deus, Guapimirim - RJ",
    time_limit: "2026-04-02",
    price: 120.0,
    status: "Cancelled",
    supplier_delivery: true,
    distance_km: 28.0,
  },
  {
    id: "ORD-006",
    client_id: "USR-013",
    final_destination: "Rua João Ferreira, Centro, São José do Vale do Rio Preto - RJ",
    time_limit: "2026-04-10",
    price: 1850.0,
    status: "Shipped",
    supplier_id: "SUP-004",
    supplier_delivery: true,
    distance_km: 55.4,
  },
  {
    id: "ORD-007",
    client_id: "USR-014",
    final_destination: "Av. Raul Veiga, Centro, Cordeiro - RJ",
    time_limit: "2026-04-12",
    price: 3200.0,
    status: "Delivered",
    supplier_id: "SUP-007",
    supplier_delivery: false,
    distance_km: 94.2,
  },
  {
    id: "ORD-008",
    client_id: "USR-017",
    final_destination: "Rua Dr. Moacyr Freijanes, Centro, Bom Jardim - RJ",
    time_limit: "2026-04-14",
    price: 680.0,
    status: "Pending",
    supplier_id: "SUP-008",
    supplier_delivery: true,
    distance_km: 42.1,
  },
  {
    id: "ORD-009",
    client_id: "USR-018",
    final_destination: "Praça Miguel de Carvalho, Centro, Cantagalo - RJ",
    time_limit: "2026-04-15",
    price: 1450.0,
    status: "Delivered",
    supplier_id: "SUP-010",
    supplier_delivery: false,
    distance_km: 110.5,
  },
  {
    id: "ORD-010",
    client_id: "USR-005",
    final_destination: "Rua Presidente Vargas, Olaria, Nova Friburgo - RJ",
    time_limit: "2026-04-18",
    price: 2100.0,
    status: "Pending",
    supplier_id: "SUP-005",
    supplier_delivery: true,
    distance_km: 65.0,
  },
  {
    id: "ORD-011",
    client_id: "USR-008",
    final_destination: "Papucaia, Zona Rural, Cachoeiras de Macacu - RJ",
    time_limit: "2026-04-20",
    price: 890.0,
    status: "Delivered",
    supplier_id: "SUP-006",
    supplier_delivery: true,
    distance_km: 38.6,
  },
  {
    id: "ORD-012",
    client_id: "USR-004",
    final_destination: "Bairro Alto, Parque Nacional, Teresópolis - RJ",
    time_limit: "2026-04-22",
    price: 1320.0,
    status: "Shipped",
    supplier_id: "SUP-009",
    supplier_delivery: false,
    distance_km: 52.8,
  },
];

export const getOrderById = (id: string): Order | undefined =>
  ORDERS.find((o) => o.id === id);

// ─── 7. Order Items
export const ORDER_ITEMS: OrderItem[] = [
  { order_id: "ORD-001", product_id: "PROD-001", quantity: 5 },
  { order_id: "ORD-001", product_id: "PROD-004", quantity: 3 },
  { order_id: "ORD-002", product_id: "PROD-003", quantity: 1 },
  { order_id: "ORD-002", product_id: "PROD-002", quantity: 1 },
  { order_id: "ORD-003", product_id: "PROD-004", quantity: 2 },
  { order_id: "ORD-004", product_id: "PROD-006", quantity: 2 },
  { order_id: "ORD-004", product_id: "PROD-007", quantity: 10 },
  { order_id: "ORD-005", product_id: "PROD-005", quantity: 1 },
  { order_id: "ORD-006", product_id: "PROD-015", quantity: 30 },
  { order_id: "ORD-006", product_id: "PROD-010", quantity: 40 },
  { order_id: "ORD-007", product_id: "PROD-014", quantity: 25 },
  { order_id: "ORD-007", product_id: "PROD-012", quantity: 1 },
  { order_id: "ORD-008", product_id: "PROD-011", quantity: 8 },
  { order_id: "ORD-008", product_id: "PROD-010", quantity: 20 },
  { order_id: "ORD-009", product_id: "PROD-016", quantity: 15 },
  { order_id: "ORD-009", product_id: "PROD-007", quantity: 4 },
  { order_id: "ORD-010", product_id: "PROD-012", quantity: 2 },
  { order_id: "ORD-011", product_id: "PROD-013", quantity: 40 },
  { order_id: "ORD-012", product_id: "PROD-009", quantity: 50 },
  { order_id: "ORD-012", product_id: "PROD-014", quantity: 6 },
];

export const getOrderItems = (orderId: string): OrderItem[] =>
  ORDER_ITEMS.filter((item) => item.order_id === orderId);

// ─── 8. Order Routes
export const ORDER_ROUTES: OrderRoute[] = [
  {
    order_id: "ORD-001",
    step: 1,
    deposit_id: "WH-002",
    truck_id: "TRK-004",
    estimated_time: "2026-03-29 11:00:00",
  },
  {
    order_id: "ORD-002",
    step: 1,
    deposit_id: "WH-001",
    truck_id: "TRK-002",
    estimated_time: "2026-03-26 14:00:00",
  },
  {
    order_id: "ORD-003",
    step: 1,
    deposit_id: "WH-002",
    truck_id: "TRK-004",
    arrived_at: "2026-03-19 10:00:00",
  },
  {
    order_id: "ORD-004",
    step: 1,
    deposit_id: "WH-004",
    truck_id: "TRK-007",
    estimated_time: "2026-04-01 10:00:00",
  },
  {
    order_id: "ORD-005",
    step: 1,
    deposit_id: "WH-005",
    truck_id: "TRK-006",
    estimated_time: "2026-04-02 11:00:00",
  },
  {
    order_id: "ORD-006",
    step: 1,
    deposit_id: "WH-006",
    truck_id: "TRK-008",
    estimated_time: "2026-04-08 11:30:00",
  },
  {
    order_id: "ORD-007",
    step: 1,
    deposit_id: "WH-007",
    truck_id: "TRK-005",
    arrived_at: "2026-04-11 09:30:00",
  },
  {
    order_id: "ORD-008",
    step: 1,
    deposit_id: "WH-008",
    truck_id: "TRK-003",
    estimated_time: "2026-04-13 14:00:00",
  },
  {
    order_id: "ORD-009",
    step: 1,
    deposit_id: "WH-007",
    truck_id: "TRK-005",
    arrived_at: "2026-04-15 10:30:00",
  },
  {
    order_id: "ORD-010",
    step: 1,
    deposit_id: "WH-003",
    truck_id: "TRK-003",
    estimated_time: "2026-04-17 10:00:00",
  },
  {
    order_id: "ORD-011",
    step: 1,
    deposit_id: "WH-004",
    truck_id: "TRK-007",
    arrived_at: "2026-04-20 14:00:00",
  },
  {
    order_id: "ORD-012",
    step: 1,
    deposit_id: "WH-001",
    truck_id: "TRK-001",
    estimated_time: "2026-04-21 14:00:00",
  },
];

export const getOrderRoute = (orderId: string): OrderRoute[] =>
  ORDER_ROUTES.filter((r) => r.order_id === orderId).sort(
    (a, b) => a.step - b.step,
  );

// ─── 9. Stock (24 records)
export const STOCK: Stock[] = [
  { id: "WH-001-PROD-001", deposit_id: "WH-001", product_id: "PROD-001", quantity: 120, arrived_at: "2026-03-10" },
  { id: "WH-001-PROD-005", deposit_id: "WH-001", product_id: "PROD-005", quantity: 15, arrived_at: "2026-03-01" },
  { id: "WH-001-PROD-009", deposit_id: "WH-001", product_id: "PROD-009", quantity: 240, arrived_at: "2026-03-18" },
  { id: "WH-001-PROD-007", deposit_id: "WH-001", product_id: "PROD-007", quantity: 45, arrived_at: "2026-03-20" },
  { id: "WH-002-PROD-004", deposit_id: "WH-002", product_id: "PROD-004", quantity: 35, arrived_at: "2026-03-12" },
  { id: "WH-002-PROD-010", deposit_id: "WH-002", product_id: "PROD-010", quantity: 80, arrived_at: "2026-03-22" },
  { id: "WH-002-PROD-013", deposit_id: "WH-002", product_id: "PROD-013", quantity: 150, arrived_at: "2026-03-14" },
  { id: "WH-003-PROD-002", deposit_id: "WH-003", product_id: "PROD-002", quantity: 20, arrived_at: "2026-03-15" },
  { id: "WH-003-PROD-008", deposit_id: "WH-003", product_id: "PROD-008", quantity: 60, arrived_at: "2026-03-05" },
  { id: "WH-003-PROD-012", deposit_id: "WH-003", product_id: "PROD-012", quantity: 40, arrived_at: "2026-03-19" },
  { id: "WH-003-PROD-014", deposit_id: "WH-003", product_id: "PROD-014", quantity: 90, arrived_at: "2026-03-21" },
  { id: "WH-004-PROD-003", deposit_id: "WH-004", product_id: "PROD-003", quantity: 50, arrived_at: "2026-03-16" },
  { id: "WH-004-PROD-006", deposit_id: "WH-004", product_id: "PROD-006", quantity: 15, arrived_at: "2026-03-17" },
  { id: "WH-004-PROD-013", deposit_id: "WH-004", product_id: "PROD-013", quantity: 200, arrived_at: "2026-03-10" },
  { id: "WH-005-PROD-013", deposit_id: "WH-005", product_id: "PROD-013", quantity: 300, arrived_at: "2026-03-11" },
  { id: "WH-005-PROD-001", deposit_id: "WH-005", product_id: "PROD-001", quantity: 80, arrived_at: "2026-03-23" },
  { id: "WH-005-PROD-010", deposit_id: "WH-005", product_id: "PROD-010", quantity: 60, arrived_at: "2026-03-24" },
  { id: "WH-006-PROD-015", deposit_id: "WH-006", product_id: "PROD-015", quantity: 180, arrived_at: "2026-03-20" },
  { id: "WH-006-PROD-004", deposit_id: "WH-006", product_id: "PROD-004", quantity: 40, arrived_at: "2026-03-22" },
  { id: "WH-007-PROD-014", deposit_id: "WH-007", product_id: "PROD-014", quantity: 110, arrived_at: "2026-03-15" },
  { id: "WH-007-PROD-016", deposit_id: "WH-007", product_id: "PROD-016", quantity: 75, arrived_at: "2026-03-18" },
  { id: "WH-007-PROD-008", deposit_id: "WH-007", product_id: "PROD-008", quantity: 30, arrived_at: "2026-03-08" },
  { id: "WH-008-PROD-010", deposit_id: "WH-008", product_id: "PROD-010", quantity: 140, arrived_at: "2026-03-21" },
  { id: "WH-008-PROD-011", deposit_id: "WH-008", product_id: "PROD-011", quantity: 50, arrived_at: "2026-03-23" },
];

export const getStockByDeposit = (depositId: string): Stock[] =>
  STOCK.filter((s) => s.deposit_id === depositId);

// ─── 10. Dashboard Stats Helper
export const getDashboardStats = (): DashboardStats => {
  const ordersInProgress = ORDERS.filter((o) => o.status === "Shipped").length;
  const pendingOrders = ORDERS.filter((o) => o.status === "Pending").length;
  const deliveredOrders = ORDERS.filter((o) => o.status === "Delivered");
  const deliveredThisMonth = deliveredOrders.length;
  const totalRevenue = deliveredOrders.reduce((acc, o) => acc + o.price, 0);
  const trucksOnRoad = TRUCKS.filter((t) => t.is_traveling).length;

  return {
    ordersInProgress,
    trucksOnRoad,
    pendingOrders,
    deliveredThisMonth,
    totalRevenue,
    avgDeliveryTime: 2.4,
  };
};

// ─── 11. Monthly Performance Report Data (12 Months)
export const MONTHLY_PERFORMANCE: MonthlyPerformanceData[] = [
  {
    month: "Jan",
    fullMonth: "Janeiro 2026",
    revenue: 34500,
    costs: 14200,
    profit: 20300,
    fuelCost: 5800,
    laborCost: 6200,
    maintenanceCost: 2200,
    ordersCount: 42,
    isPoi: true,
    poi: "Inauguração da Rota Serrana Integrada (BR-040 & Terê-Fri)",
  },
  {
    month: "Feb",
    fullMonth: "Fevereiro 2026",
    revenue: 29800,
    costs: 12900,
    profit: 16900,
    fuelCost: 5100,
    laborCost: 5900,
    maintenanceCost: 1900,
    ordersCount: 38,
    isPoi: false,
  },
  {
    month: "Mar",
    fullMonth: "Março 2026",
    revenue: 43200,
    costs: 18100,
    profit: 25100,
    fuelCost: 7400,
    laborCost: 8100,
    maintenanceCost: 2600,
    ordersCount: 56,
    isPoi: true,
    poi: "Pico de Safra de Hortaliças em Teresópolis & São José",
  },
  {
    month: "Apr",
    fullMonth: "Abril 2026",
    revenue: 37800,
    costs: 16500,
    profit: 21300,
    fuelCost: 6700,
    laborCost: 7300,
    maintenanceCost: 2500,
    ordersCount: 48,
    isPoi: false,
  },
  {
    month: "May",
    fullMonth: "Maio 2026",
    revenue: 41500,
    costs: 17200,
    profit: 24300,
    fuelCost: 7000,
    laborCost: 7600,
    maintenanceCost: 2600,
    ordersCount: 51,
    isPoi: false,
  },
  {
    month: "Jun",
    fullMonth: "Junho 2026",
    revenue: 51000,
    costs: 21800,
    profit: 29200,
    fuelCost: 9100,
    laborCost: 9500,
    maintenanceCost: 3200,
    ordersCount: 64,
    isPoi: true,
    poi: "Expansão das Câmaras Frigoríficas de Nova Friburgo & Lumiar",
  },
  {
    month: "Jul",
    fullMonth: "Julho 2026",
    revenue: 46200,
    costs: 19400,
    profit: 26800,
    fuelCost: 8000,
    laborCost: 8600,
    maintenanceCost: 2800,
    ordersCount: 59,
    isPoi: false,
  },
  {
    month: "Aug",
    fullMonth: "Agosto 2026",
    revenue: 49500,
    costs: 20500,
    profit: 29000,
    fuelCost: 8500,
    laborCost: 9000,
    maintenanceCost: 3000,
    ordersCount: 62,
    isPoi: false,
  },
  {
    month: "Sep",
    fullMonth: "Setembro 2026",
    revenue: 55800,
    costs: 23200,
    profit: 32600,
    fuelCost: 9800,
    laborCost: 10100,
    maintenanceCost: 3300,
    ordersCount: 71,
    isPoi: true,
    poi: "Integração de Rastreamento PostGIS & Roteamento Valhalla na Serra",
  },
  {
    month: "Oct",
    fullMonth: "Outubro 2026",
    revenue: 52100,
    costs: 21900,
    profit: 30200,
    fuelCost: 9200,
    laborCost: 9600,
    maintenanceCost: 3100,
    ordersCount: 66,
    isPoi: false,
  },
  {
    month: "Nov",
    fullMonth: "Novembro 2026",
    revenue: 58900,
    costs: 24800,
    profit: 34100,
    fuelCost: 10300,
    laborCost: 10800,
    maintenanceCost: 3700,
    ordersCount: 78,
    isPoi: false,
  },
  {
    month: "Dec",
    fullMonth: "Dezembro 2026",
    revenue: 68400,
    costs: 27900,
    profit: 40500,
    fuelCost: 11800,
    laborCost: 12000,
    maintenanceCost: 4100,
    ordersCount: 89,
    isPoi: true,
    poi: "Recorde de Entregas de Fim de Ano & Distribuição de Cervejas e Queijos Serranos",
  },
];

// ─── 12. Freight Costs
export const FREIGHT_COSTS = [
  {
    order_id: "ORD-001",
    fuel_cost: 85.0,
    labor_cost: 110.0,
    maintenance_cost: 15.0,
    total_cost: 210.0,
    calculated_at: "2026-03-24 09:15:00",
  },
  {
    order_id: "ORD-002",
    fuel_cost: 150.0,
    labor_cost: 300.0,
    maintenance_cost: 45.0,
    total_cost: 495.0,
    calculated_at: "2026-03-25 10:30:00",
  },
  {
    order_id: "ORD-003",
    fuel_cost: 25.0,
    labor_cost: 40.0,
    maintenance_cost: 5.0,
    total_cost: 70.0,
    calculated_at: "2026-03-20 11:00:00",
  },
  {
    order_id: "ORD-004",
    fuel_cost: 180.0,
    labor_cost: 260.0,
    maintenance_cost: 38.0,
    total_cost: 478.0,
    calculated_at: "2026-03-28 14:00:00",
  },
  {
    order_id: "ORD-006",
    fuel_cost: 115.0,
    labor_cost: 160.0,
    maintenance_cost: 22.0,
    total_cost: 297.0,
    calculated_at: "2026-04-06 16:45:00",
  },
  {
    order_id: "ORD-007",
    fuel_cost: 210.0,
    labor_cost: 340.0,
    maintenance_cost: 52.0,
    total_cost: 602.0,
    calculated_at: "2026-04-09 10:00:00",
  },
];

export const getFreightCostByOrder = (orderId: string) =>
  FREIGHT_COSTS.find((fc) => fc.order_id === orderId);
